Webp cover support
NickvisionApps/Tagger pull request #254
Opened 2023-08-15 09:35 UTC by fsobolev

Closes #253 

1. In MainWindow `image/*` filter in FileDialog was replaced with jpeg/png/bmp/webp, because filter with wildcard crashes portal in KDE (bad KDE, bad). I hope these 4 formats are enough (and I think it's better to have the list of formats that  we can verify instead of allowing any images).
2. `webp-pixbuf-loader` was added to flatpak build
3. Because in flatpak we install webp loader not to main gdk-pixbuf directory (it's read-only), we have to explicitetly load modules from new directory, so there are changes in `Program.cs`. This doesn't affect other packages, local build in fedora loads `webp-pixbuf-loader` installed with dnf without any problem since it's in main directory.

2023-08-15 10:03 UTC, nlogozzo commented
Can you or @soumyaDghosh update snap file as well?

2023-08-15 10:03 UTC, nlogozzo commented
Also, if you could update the changelog :)

2023-08-15 10:04 UTC, fsobolev commented
I forgot to test export... Well, I suppose it will work on GNOME, but on KDE it crashes again because `GetFirstAlbumArtMimeType` returns `image/*` for webp. Anything we can do with this?

2023-08-15 10:13 UTC, nlogozzo commented
> **EDIT**: Probably time for yet another ATL issue 😅 

If we set the mimetype ourselves will it save? Like if we set it to image/png, inage/jpg etc? I don't remember what the exact issue was....does atldotnet always just return image/*? If so then yes I'd open an issue there to remember specific image types.

2023-08-15 10:16 UTC, fsobolev commented
> > **EDIT**: Probably time for yet another ATL issue 😅
> 
> If we set the mimetype ourselves will it save? Like if we set it to image/png, inage/jpg etc? I don't remember what the exact issue was....does atldotnet always just return image/*? If so then yes I'd open an issue there to remember specific image types.

I looked at ATL code, yes, it returns `image/*` when it can't detect image format, and there are no checks for WEBP at all https://github.com/Zeugma440/atldotnet/blob/main/ATL/Utils/ImageUtils.cs#L88

2023-08-15 10:22 UTC, soumyaDghosh commented
> Can you or @soumyaDghosh update snap file as well?

Webp libraries are in gnome-sdk and probably supported by ffmpeg-sdk also.

2023-08-15 10:24 UTC, fsobolev commented
> Webp libraries are in gnome-sdk and probably supported by ffmpeg-sdk also.

`libwebp` is in flatpak GNOME platform as well, but `webp-pixbuf-loader` was missing. You can check by simply trying to import webp cover - if the app crashes, then loader is missing.

2023-08-16 02:27 UTC, nlogozzo requested changes

2023-08-16 02:27 UTC, nlogozzo commented on NickvisionTagger.GNOME/Program.cs
> +              * Fixed an issue where using WebP image for album art caused crash
should be `caused a crash` and then needs to be added to metainfo xml file as well

2023-08-16 02:32 UTC, nlogozzo commented
Code looks good to me, just waiting for new `atldotnet` release to fix the mimetype.

2023-08-16 06:35 UTC, merged