Fixes
NickvisionApps/Tagger pull request #396
Opened 2023-11-06 21:31 UTC by nlogozzo

Fixes #395

2023-11-06 23:34 UTC, kissthermite commented
> @kissthermite Could you test this build: https://github.com/NickvisionApps/Tagger/actions/runs/6776895782

sure! will let you know in a moments

2023-11-07 00:13 UTC, kissthermite commented
Using custom format string `/%albumartist%/%album%/%artist% - %title%` with `Limit File Name Characters` setting turn on does work as expected for others limited characters except `/`

---

tag to file name conversion with aforementioned format string with limited character being `:`
![](https://media.discordapp.net/attachments/1139923418767175764/1171234712497426473/1.png?ex=655bf053&is=65497b53&hm=59dce283b2894d0305394bf2ea1fbb4d6657c6099f22748aef4fb3e3fa9b0f3d&=&width=575&height=626)

will give this output: `/Kotono Nagase (CV_Mirai Tachibana)/song for you(Kotono version)/Kotono Nagase (CV_Mirai Tachibana) - song for you(Kotono version).flac`
![](https://media.discordapp.net/attachments/1139923418767175764/1171234735444471819/2.png?ex=655bf059&is=65497b59&hm=e41fc14f2829a1b0c3126bd88e69b278cdd2dc4b573895fe03ccc18270731e61&=&width=575&height=626)

---

tag to file name conversion with aforementioned format string with limited character being `/`
![](https://media.discordapp.net/attachments/1139923418767175764/1171234758295031958/3.png?ex=655bf05e&is=65497b5e&hm=2897f7438f58f6ad0172e88b0c7230c1c9b1ec77a45d1a6ff092d6b7be743ec4&=&width=575&height=626)

will give this output: `/SQUARE ENIX MUSIC/NieR Gestalt & NieR Replicant Original Soundtrack/SQUARE ENIX MUSIC - Song of the Ancients /Devola.flac`
![](https://media.discordapp.net/attachments/1139923418767175764/1171234790456967238/5.png?ex=655bf066&is=65497b66&hm=8b70e89fc694c2b14e3512f528b9174f1e7ad1f7036fe3ca23f2fc7a84308171&=&width=575&height=626)

---

2023-11-07 01:29 UTC, nlogozzo commented
> tag to file name conversion with aforementioned format string with limited character being /

Well now with the new algorithm `/` means new directory. But you want it where if the `/` was contained in a tag property and now the format string, to not count as a new directory, correct?

I think I can do that.

2023-11-07 01:34 UTC, kissthermite commented
>But you want it where if the `/` was contained in a tag property and now the format string, to not count as a new directory, correct?

Correct indeed.

2023-11-07 03:10 UTC, nlogozzo commented
@fsobolev If you could make sure the algorithm in this commit still holds: https://github.com/NickvisionApps/Tagger/pull/396/commits/325b0f408260cd0d5a69dfc756fda2e213346a14

2023-11-07 03:16 UTC, nlogozzo commented
> > But you want it where if the `/` was contained in a tag property and now the format string, to not count as a new directory, correct?
> 
> Correct indeed.

@kissthermite Try this build: https://github.com/NickvisionApps/Tagger/actions/runs/6779510126?pr=396

P.S. Thanks for testing and sorry for messing up your library structure with these tests 🫠

2023-11-07 03:33 UTC, nlogozzo commented
> > > But you want it where if the `/` was contained in a tag property and now the format string, to not count as a new directory, correct?
> > 
> > 
> > Correct indeed.
> 
> @kissthermite Try this build: https://github.com/NickvisionApps/Tagger/actions/runs/6779510126?pr=396
> 
> P.S. Thanks for testing and sorry for messing up your library structure with these tests 🫠

Sorry I lied, please try this build: https://github.com/NickvisionApps/Tagger/actions/runs/6779656223/job/18427058390

If a tag property contains `/`, regardless of using Limit Filename Characters, it will not create a new directory. Only if the format string explicitly contains a `/`, then it will.

2023-11-07 03:41 UTC, kissthermite commented
> P.S. Thanks for testing and sorry for messing up your library structure with these tests 🫠

Don't worries my actual music library are stored on /var/home/kissthermite/Jellyfin Server Media/Music
![](https://media.discordapp.net/attachments/1139923418767175764/1171292577228652614/Screenshot_from_2023-11-07_10-38-05.png?ex=655c2637&is=6549b137&hm=e41b2cdf00e6564d702f52d4c95b13752d0b3c17786f54440f1ab09f887e7cd9&=&width=575&height=626)
The one on Downloads folder are just a copy for testing purpose XD.

2023-11-07 03:50 UTC, kissthermite commented
> If a tag property contains `/`, regardless of using Limit Filename Characters, it will not create a new directory. Only if the format string explicitly contains a `/`, then it will.

Just tested and indeed it does behave the way you said whether `File Name Characters` turn on/off. Good job @nlogozzo! and enjoy your well deserved rest tonight.

2023-11-07 03:52 UTC, nlogozzo commented
> Just tested and indeed it does behave the way you said whether `Limit File Name Characters` turn on/off. Good job @nlogozzo! and enjoy your well deserved rest tonight.

Yay, glad it's working as expected now! Once @fsobolev approves of the rest of this PR, I will release a beta. 

If you have any other issues/feature requests please try to report them before Wednesday that way I can implement them all on Wednesday and then get a stable out by Friday 😅

2023-11-07 04:09 UTC, kissthermite commented
> If you have any other issues/feature requests please try to report them before Wednesday that way I can implement them all on Wednesday and then get a stable out by Friday 😅

Actually there's one thing.
![](https://media.discordapp.net/attachments/1139923418767175764/1171299486933459034/Screenshot_from_2023-11-07_11-02-55.png?ex=655c2ca7&is=6549b7a7&hm=3a0534944fa7e011bb69834a4c245c4203a14b91c02cb25c35e0765eb1b61fae&=)
With `Limit File Name Characters` turn on, Tagger ignored space before, between & after that limited characters, is that the intended behavior?

2023-11-07 04:13 UTC, nlogozzo commented
> With Limit File Name Characters turn on, Tagger ignored space before, between & after that limited characters, is that the intended behavior?

Hmm...no it's not intended. Will take a look at it tomorrow to see what's going on.

2023-11-07 08:41 UTC, DaPigGuy requested changes

2023-11-07 08:41 UTC, DaPigGuy commented on NickvisionTagger.Shared/Models/MusicFile.cs
> +                replace = replace.Replace(RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? '\\' : '/', '_');
`Path.DirectorySeparatorChar`

2023-11-07 08:41 UTC, DaPigGuy commented on NickvisionTagger.Shared/Models/MusicFile.cs
> +            _invalidWindowsFilenameCharacters.Remove('/');
Well, `_invalidWindowsFilenameCharacters` is only used on non-Windows platforms for the Limit Filename Characters preference anyway, so maybe just not include `/` :sweat_smile:

2023-11-07 08:41 UTC, DaPigGuy commented on NickvisionTagger.Shared/Models/MusicFile.cs
> +            _invalidWindowsFilenameCharacters.Remove('/');
`_invalidSystemFilenameCharacters.Remove(Path.DirectorySeparatorChar);`

2023-11-08 00:56 UTC, nlogozzo commented
>With Limit File Name Characters turn on, Tagger ignored space before, between & after that limited characters, is that the intended behavior?

@kissthermite Can't reproduce...
Here's WinUI:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/c7022d96-ef6b-4507-a37f-63f5aa7c60a5)
Here's GNOME:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/867051af-b768-4e01-b456-b46006e6c700)

I think it just seems every small in GNOME but the space is indeed there.

2023-11-08 02:15 UTC, kissthermite commented
Yeah. My bad just check it again and indeed it's just a very tiny space.

2023-11-08 02:23 UTC, merged

2023-11-08 02:23 UTC, nlogozzo commented
I was going to release a beta but decided against it since it's almost Friday and if any bugs come up before then I will fix them and just release stable. Since your issue was confirmed to be fixed, no need for a beta.